services:
  database:
    container_name: finance_db
    image: mysql:8.4.0
    env_file:
      - ./backend/.env.development
    volumes:
      - ./database/finances.sql:/docker-entrypoint-initdb.d/finances.sql:ro
    ports:
      - 3306:3306
  backend:
    container_name: finance_backend
    image: finance_backend_img
    build: ./backend
    depends_on:
      - database
    ports:
      - 4000:3000
