services:
  backend:
    container_name: finance_backend
    image: finance_backend_img
    build: ./backend
    volumes:
      - ./database:/app/src/database/:rw
  frontend:
    container_name: finance_frontend
    image: finance_frontend_img
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 80:80
